spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8082

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG